### PR TITLE
Fix #3 Minimal test for JDT formatter

### LINKED ISSUE #3: Minimal test for JDT formatter

### PR DESCRIPTION
**Pull request by ppalaga**
@dyadix could you please review as described here in GitHub help? https://help.github.com/articles/reviewing-proposed-changes-in-a-pull-request/

### CODE REVIEW

**Comment by ppalaga** [comment]
About this PR:

* 3ed1b92 is the main payload of this pull request. The main idea is to have a bunch of test files under [tck/src/test/resources](https://github.com/ec4j/editorconfig-java-domain/tree/3ed1b92eb72ac2661473a97633ecca00a54dd53f/tck/src/test/resources), out of which we generate JUnit test cases using [generate-test-classes.groovy](https://github.com/ec4j/editorconfig-java-domain/blob/3ed1b92eb72ac2661473a97633ecca00a54dd53f/tck/src/build/groovy/generate-test-classes.groovy)
* There is a thin SPI for the formatter implementations: [Formatter](https://github.com/ec4j/editorconfig-java-domain/blob/3ed1b92eb72ac2661473a97633ecca00a54dd53f/tck-spi/src/main/java/org/ec4j/java/domain/tck/spi/Formatter.java). I have also added the implementation for JDT: [JdtFormatter](https://github.com/ec4j/editorconfig-java-domain/blob/3ed1b92eb72ac2661473a97633ecca00a54dd53f/jdt/src/main/java/org/ec4j/java/domain/jdt/JdtFormatter.java)
* 55367ce adds a README that explains some aspects of 3ed1b92
* 84cfb78 adds Maven wrapper, mainly to simplify the provisioning of the right Maven version on CI (Travis, AppVeyor)
* d4fb26e adds config for CI services: we build and test on Windows (Java 8) and Linux (Java 8 and 11). the tests we have now for JDT are passing on all JREs and plattforms.

**Comment by ppalaga** [comment]
c630091 adds [IjFormatter](https://github.com/ec4j/editorconfig-java-domain/pull/4/commits/c630091eb4ceecdd294f8d2446396bff6d4de0f7#diff-a9d3b2ad8e2a200fb102f7d866738698R39). It relies on the IJ `format.sh` script built from sources in the [ij-build Maven module](https://github.com/ec4j/editorconfig-java-domain/pull/4/commits/c630091eb4ceecdd294f8d2446396bff6d4de0f7#diff-d6abbac4eac78e73b730282779fba5e3R28).

The tests are run via [`ij` Maven profile](https://github.com/ec4j/editorconfig-java-domain/pull/4/commits/c630091eb4ceecdd294f8d2446396bff6d4de0f7#diff-7a12c99b07270345b07419e9f415e25dR153). Travis is run on both OpenJDK 8 and 11.

Apparently the IJ build does not work on Java 11: https://travis-ci.org/ec4j/editorconfig-java-domain/jobs/468467419#L4712

The [Java 8 build still runs](https://travis-ci.org/ec4j/editorconfig-java-domain/jobs/468467418) as I am writing this. It is expected fail on the two tab tests. The ij tag 182.5107.16 that is currently built probably does not support `indet_size` and `indent_style` editorconfig properties yet.

Any feedback is welcome.

**Comment by ppalaga** [comment]
> it's better to take the build from Maven-like repository: https://www.jetbrains.com/intellij-repository/releases. There is an artifact ideaIC-.zip.

Yes, thanks for the suggestion, that would clearly speedup running our tests. 

The question is only if the IJ release cadence is fast enough. I guess sooner or later, going through the new editorconfig props and adding tests we will come to a point where some fix will need to be done in IJ. Testing against a fresh build from sources would have the advantage that such a fix can be verified even before it is merged to IJ master. WDYT?

Actually, what level of editorconfig support should I expect from the lastest build available in the public maven repo? When I switch to it, should I expect the two TAB tests in [1] pass?

[1] https://github.com/ec4j/editorconfig-java-domain/tree/c630091eb4ceecdd294f8d2446396bff6d4de0f7/tck/src/test/resources/basic/indent_style/tab

**Comment by dyadix** [comment]
I guess the failing test is a bug in command-line formatter which simply doesn't take `.editorconfig` into account. It does some magic to overwrite project settings for user's own code style explicitly given as a command-line parameter. I'll investigate it.
I'm going to run the tests also locally before merging changes to master. For that I'll probably add the test to IntelliJ EditorConfig plug-in test suite as well. Besides I guess the builds are frequent enough for compliance verification, usually daily. I don't think it's a problem if a master branch appears broken, say, for a day. The fix will anyway come shortly, usually the next day. So downloading builds instead of building from sources shouldn't be any problem.

**Comment by ppalaga** [comment]
> I guess the failing test is a bug in command-line formatter which simply doesn't take `.editorconfig` into account. It does some magic to overwrite project settings for user's own code style explicitly given as a command-line parameter. I'll investigate it.

Thanks, I created https://github.com/ec4j/editorconfig-java-domain/issues/5 to track it.

> I'm going to run the tests also locally before merging changes to master. For that I'll probably add the test to IntelliJ EditorConfig plug-in test suite as well. 

+1

Actually, I am trying to design the test suite here so that it can be run also as a part of IJ or JDT build. So if want to somehow embed this test suite in IJ, that would be highly welcome.

> Besides I guess the builds are frequent enough for compliance verification, usually daily. I don't think it's a problem if a master branch appears broken, say, for a day. The fix will anyway come shortly, usually the next day. So downloading builds instead of building from sources shouldn't be any problem.

Indeed a day, or a couple of days is acceptable. Let me switch to the maven repo.

**Comment by ppalaga** [comment]
Yeah, much faster like this. Under 4 mins.

@dyadix could you please merge if you do not have any more suggestions?

**Pull request merged**
